del /Q "%userprofile%\.vimrc"
mklink "%userprofile%\.vimrc" "%userprofile%\dotfiles\.vimrc"
del /Q "%userprofile%\.vim" 
mklink /d "%userprofile%\.vim" "%userprofile%\dotfiles\.vim"
del /Q "%userprofile%\.hyper.js" 
mklink "%userprofile%\.hyper.js" "%userprofile%\dotfiles\.hyper.js"
del /Q "%userprofile%\.gitconfig" "%userprofile%\dotfiles\.gitconfig"
mklink "%userprofile%\.gitconfig" "%userprofile%\dotfiles\.gitconfig"
del /Q "%appdata%\Code\User\settings.json" 
mklink "%appdata%\Code\User\settings.json" "%userprofile%\dotfiles\vscode\ms-settings.json"
del /Q "%appdata%\Notepad++\config.xml"
mklink "%appdata%\Notepad++\config.xml" "%userprofile%\dotfiles\Notepad++\config.xml"
del /Q "%userprofile%\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"
mklink /D "%userprofile%\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1" "%userprofile%\dotfiles\Microsoft.PowerShell_profile.ps1"
